Repository openshift/machine-api-provider-aws, pull requests merged in 2022-07, with the labels that each got.

#44 Bug 2060068: check securityGroupIDs for emptiness
  pkg/actuators/machine/instances.go
Labels: approved, bugzilla/valid-bug, bugzilla/severity-medium, lgtm

#46 Bug 2106733: Fix panic when accessing nil machine annotations map
  pkg/actuators/machine/reconciler.go
Labels: bugzilla/severity-high, approved, bugzilla/valid-bug, lgtm

#43 pkg/actuators/machineset/controller: Fix %s in scale-from-zero logging
  pkg/actuators/machineset/controller.go
Labels: approved, lgtm

#48 [release-4.10] Bug 2109124: Validate unknown regions using AWS API
  pkg/actuators/machine/actuator.go
  pkg/actuators/machine/actuator_test.go
  pkg/actuators/machine/controller_test.go
  pkg/actuators/machine/machine_scope.go
  pkg/actuators/machine/machine_scope_test.go
  pkg/actuators/machine/reconciler_test.go
  pkg/client/client.go
  pkg/client/mock/client_generated.go
Labels: bugzilla/severity-high, approved, backport-risk-assessed, bugzilla/valid-bug, lgtm, cherry-pick-approved
