Repository openshift/machine-api-provider-aws, pull requests merged in 2022-01, with the labels that each got.

#18 Bug 2040504: Ensure IOPS setting is honoured on all supported block device types
  pkg/actuators/machine/instances.go
Labels: approved, bugzilla/valid-bug, bugzilla/severity-medium, lgtm

#19 Bug 2040376: Update map of supported aws instance types
  pkg/actuators/machineset/ec2_instance_types.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#15 CFE-68 : user defined resource tags on EC2 instances updatable
  pkg/actuators/machine/instances_test.go
  pkg/actuators/machine/reconciler.go
  pkg/actuators/machine/utils.go
Labels: approved, lgtm
